export const mockProducts = [
  {
    id: 1,
    title: 'Camiseta Urbana de Algodón',
    price: 19.99,
    description: 'Una camiseta cómoda y moderna para uso diario con corte relajado.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: { rate: 4.3, count: 110 },
  },
  {
    id: 2,
    title: 'Reloj Minimalista',
    price: 89.9,
    description: 'Reloj elegante con correa de acero inoxidable ideal para cualquier outfit.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.9, count: 80 },
  },
  {
    id: 3,
    title: 'Zapatillas Deportivas',
    price: 55.5,
    description: 'Zapatillas ligeras y resistentes pensadas para entrenamiento y paseo.',
    category: "men's clothing",
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.1, count: 90 },
  },
  {
    id: 4,
    title: 'Bolso Casual para Mujer',
    price: 34.0,
    description: 'Bolso moderno con varios compartimentos y cierre seguro.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    rating: { rate: 4.0, count: 70 },
  },
  {
    id: 5,
    title: 'Auriculares Inalámbricos',
    price: 45.75,
    description: 'Auriculares bluetooth con cancelación de ruido y batería de larga duración.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: { rate: 4.6, count: 200 },
  },
  {
    id: 6,
    title: 'Mochila de Viaje',
    price: 49.99,
    description: 'Mochila resistente a la lluvia con múltiples bolsillos y diseño ergonómico.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: { rate: 4.5, count: 145 },
  },
  {
    id: 7,
    title: 'Vestido Floral',
    price: 39.95,
    description: 'Vestido ligero con estampado floral ideal para temporada de verano.',
    category: "women's clothing",
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    rating: { rate: 4.2, count: 95 },
  },
  {
    id: 8,
    title: 'Lámpara LED Multifunción',
    price: 27.5,
    description: 'Lámpara con control táctil, temperatura de color ajustable y puerto USB.',
    category: 'electronics',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: { rate: 4.4, count: 130 },
  },
  {
    id: 9,
    title: 'Anillo de Plata Fina',
    price: 24.99,
    description: 'Anillo minimalista con acabado pulido para eventos especiales.',
    category: 'jewelery',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: { rate: 4.7, count: 45 },
  },
];
